version: "3.7"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend/
    ports:
      - 3001:3000
    volumes:
      - ./:/webcrawler
      - '/webcrawler/frontend/node_modules'
    stdin_open: true
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: webcrawler
      CHOKIDAR_USEPOLLING: "true"
